"""empty message

Revision ID: 13ca3cba61f0
Revises: 6752fcfb5862
Create Date: 2019-03-24 21:31:40.027876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ca3cba61f0'
down_revision = '6752fcfb5862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn', sa.Column('turn', sa.Integer(), nullable=False))
    op.drop_constraint('turn_turn_uuid_key', 'turn', type_='unique')
    op.drop_column('turn', 'turn_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turn', sa.Column('turn_uuid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('turn_turn_uuid_key', 'turn', ['turn_uuid'])
    op.drop_column('turn', 'turn')
    # ### end Alembic commands ###
